# pnpm workspace configuration - defines monorepo structure for local package linking
packages:
  - 'apps/*'      # Applications (web, worker) - deployable services
  - 'packages/*'  # Shared packages (core, contracts, db) - internal libraries
